### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by dbeauchaine**
Refactored the database searches for individual and team. Added NIBB and team for S and PA

### CODE REVIEW

**Comment by cletus87408** [comment]
Ok.  Code is on develop.

**Comment by dbeauchaine** [comment]
Excellent. Thanks.

On Jul 27, 2017 11:12 AM, "Bob Beauchaine" <notifications@github.com> wrote:

Ok. Code is on develop.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/cletus87408/PlayBall/pull/6#issuecomment-318442700>,
or mute
the thread

**Comment by cletus87408** [comment]
New refactoring in place.  I pulled your methods out into separate extension method classes for reusability changed the call sites slightly.  It's more modular now.


Sent via the Samsung GALAXY S® 5, an AT&T 4G LTE smartphone

-------- Original message --------

**Comment by dbeauchaine** [comment]
great. I'll take a look at it when I get home, and try to learn to do this
in the future.

**Comment by cletus87408** [comment]
No worries.  You did a good thing for your level of experience.  This falls well into the category of architecture and design, which you can only gain with experience.  Half of what I did you don't even have the domain knowledge to duplicate on your own.   Your work is plenty up-to-snuff for an intern.  

And always remember - ask two software engineers how to solve a problem an you'll get three answers.

No doubt you're asking yourself "Why the hell didn't he do it this way in the first place?"  To which the only answer is "don't overdesign unnecessarily".  Add features as soon as you know you'll need them, but not too soon.   For one example file, doing it the straightforward way make perfect sense.  As soon as it became obvious that one query was going to be used over and over again. refactoring became almost mandatory.  You are now practicing agile development.

**Comment by cletus87408** [comment]
The other thing I would add is that this was a simple refactoring to test because we have something like 95 tests in place.  I could make the changes and be confident that if the unit tests passed, I hadn't broken anything.  Still, I too need to add a few additional tests now that I broke the find-by-name and filter-by-date queries into separate pieces.  No more time at lunch though.

**Pull request merged**
